/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.jpon.ka;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;

import javax.json.Json;
import javax.json.JsonArray;
import javax.json.JsonObject;
import javax.json.JsonReader;
import javax.json.JsonValue;

public class GenerateBoxApp {
	public static void main(String[] args) throws Exception {
		File dir = new File("H:\\電話帳\\作業\\昭和38年2月1日大阪市50音別電話番号簿\\reconstruct");
		for (File file : dir.listFiles()) {
			if (!file.getName().endsWith("-gt.json")) {
				continue;
			}
			String num = file.getName().substring(0, 4);
			try (PrintWriter out = new PrintWriter(
					new OutputStreamWriter(new FileOutputStream(new File(dir, num + ".box")), "UTF-8"))) {
				try (JsonReader jr = Json.createReader(new FileInputStream(file))) {
					JsonObject im = jr.readObject();
					int ih = im.getInt("height");
					JsonArray gts = im.getJsonArray("gts");
					for (JsonValue v : gts) {
						JsonObject o = (JsonObject) v;
						String text = o.getString("text");
						JsonArray bounds = o.getJsonArray("bounds");
						int x = bounds.getInt(0);
						int y = bounds.getInt(1);
						int w = bounds.getInt(2);
						int h = bounds.getInt(3);
						String box = " "+x+" "+(ih - y - h)+" "+(x+w)+" "+(ih - y)+" 0";
						for (char c : text.toCharArray()) {
							out.print(c);
							out.println(box);
						}
						out.print('\t');
						out.println(box);
					}
				}
			}
		}
	}
}
